const u = (id: string, w = 1600) => `https://images.unsplash.com/${id}?q=80&w=${w}&auto=format&fit=crop`;

export const IMG = {
  hero: u("photo-1634822930432-0594057fdff2", 2200),
  doorDark: u("photo-1537199322506-85bfd51c0601"),
  handle: u("photo-1670100191868-84c3809e0f00"),
  hotelCorridor: u("photo-1760276148666-1fd62b875fa6"),
  hotelDark: u("photo-1763142106375-fb47c275ed45", 2000),
  grain: u("photo-1644931551533-02906718127f"),
  bathroom: u("photo-1620626011761-996317b8d101"),
  interior: u("photo-1600607687939-ce8a6c25118c"),
  interiorAlt: u("photo-1615873968403-89e068629265"),
  bathroomAlt: u("photo-1552321554-5fefe8c9ef14"),
  living: u("photo-1600566753086-00f18fb6b3ea"),
  factoryFloor: "/factory/factory-floor.jpg",
  blueprint: u("photo-1721244654394-36a7bc2da288"),
};

export const DOORS = [
  {
    slug: "fire-retardant",
    name: "Fire Retardant",
    wood: "Engineered Core",
    tagline: "Tested for safety and structural integrity.",
    image: IMG.doorDark,
    description: "Our fire-retardant doors are designed to meet stringent safety standards, providing critical structural integrity during emergencies without compromising on architectural aesthetics.",
    appearance: "Customizable based on external veneer or laminate finish.",
    applications: ["Commercial spaces", "High-rise residential", "Hospitality", "Institutions"],
    finishes: ["Veneer", "Laminate", "Painted", "PU Finish"],
    customisation: "Fire ratings available from 30 to 120 minutes per project specifications.",
    frames: ["Solid Hardwood Frame", "LVL Frame", "BWP LVL Frame"],
    suitability: "Essential for projects requiring strict fire safety compliance.",
  },
  {
    slug: "engineered-laminated",
    name: "Engineered Laminated",
    wood: "Engineered Wood",
    tagline: "Durable and warp-resistant construction.",
    image: IMG.interiorAlt,
    description: "Engineered laminated doors offer exceptional dimensional stability. They resist warping, shrinking, and swelling, making them ideal for long-term durability in varied environmental conditions.",
    appearance: "Uniform and flawless, available in a wide spectrum of laminate designs.",
    applications: ["Residential interiors", "Offices", "Educational institutions", "Healthcare"],
    finishes: ["High-pressure laminate (HPL)", "Textured laminate", "Solid color laminate"],
    customisation: "Vast array of laminate selections, custom grooving, and edge-banding options.",
    frames: ["LVL Frame", "Steamed Beech Frame"],
    suitability: "Perfect for high-traffic areas demanding low maintenance and high durability.",
  },
  {
    slug: "veneer-finish",
    name: "Veneer Finish",
    wood: "Mixed Hardwoods & Veneer",
    tagline: "Premium natural wood aesthetics.",
    image: IMG.interior,
    description: "Veneer finish doors combine the structural strength of an engineered core with the rich, natural beauty of real wood veneers, delivering a premium look that elevates any interior.",
    appearance: "Natural wood grain patterns, unique to each sheet of veneer.",
    applications: ["Luxury residences", "Executive offices", "Boutique hotels"],
    finishes: ["Natural Polish", "Melamine Polish", "PU Polish", "Matt / Gloss"],
    customisation: "Extensive selection of wood veneers (Teak, Walnut, Oak, etc.) and matching grain patterns.",
    frames: ["Solid Teak Frame", "LVL Frame with matching veneer"],
    suitability: "Ideal for premium projects where the authentic look and feel of natural wood is desired.",
  },
  {
    slug: "pu-finish",
    name: "PU Finish",
    wood: "Engineered Core / MDF",
    tagline: "Sleek, modern, and highly durable surface.",
    image: IMG.bathroom,
    description: "Polyurethane (PU) finish doors provide a flawless, sleek surface that is not only visually stunning but also highly resistant to scratches, moisture, and everyday wear.",
    appearance: "Ultra-smooth surface available in vibrant solids or sophisticated mattes.",
    applications: ["Modern apartments", "Contemporary offices", "Designer boutiques"],
    finishes: ["High Gloss PU", "Matt PU", "Satin PU"],
    customisation: "Any RAL color shade, combined with CNC routed patterns or metallic inlays.",
    frames: ["Steamed Beech Frame", "LVL Frame (PU coated)"],
    suitability: "Best suited for ultra-modern, minimalist spaces requiring a pristine, flawless finish.",
  },
  {
    slug: "flush-doors",
    name: "Flush Doors",
    wood: "Hardwood / Pine Core",
    tagline: "Clean, minimalist, and versatile.",
    image: IMG.living,
    description: "The quintessential minimalist door. Our flush doors are engineered with a solid blockboard or tubular core, ensuring a perfectly flat surface that integrates seamlessly into any architectural style.",
    appearance: "Perfectly flat and unadorned, acting as a blank canvas.",
    applications: ["Residential", "Commercial", "Utility areas", "Basements"],
    finishes: ["Paint grade", "Laminate ready", "Veneer ready"],
    customisation: "Core options (solid, tubular, honeycomb), custom sizing, and edge lipping.",
    frames: ["LVL Frame", "Pine Frame", "BWP LVL Frame"],
    suitability: "A versatile, cost-effective solution for large-scale developments and minimalist designs.",
  },
  {
    slug: "moulded-doors",
    name: "Moulded Doors",
    wood: "HDF Skin",
    tagline: "Classic architectural detailing.",
    image: IMG.handle,
    description: "Moulded doors feature high-density fibreboard (HDF) skins pressed into classic panel designs. They offer the traditional look of solid paneled doors with the stability of modern engineering.",
    appearance: "Classic raised or recessed panel designs with simulated wood grain or smooth finishes.",
    applications: ["Traditional homes", "Residential developments", "Heritage properties"],
    finishes: ["Primed for painting", "Pre-finished painted", "Textured"],
    customisation: "Various panel configurations (2-panel, 4-panel, 6-panel) and sizing options.",
    frames: ["LVL Frame", "Steamed Beech Frame"],
    suitability: "Excellent for projects seeking classic architectural aesthetics on a developer's budget.",
  }
];

export const FRAMES_PRODUCTS = [
  {
    slug: "solid-teak-frames",
    name: "Solid Teak Wood Frames",
    kind: "Solid Wood",
    tagline: "Traditional solid timber, machined with precision.",
    image: IMG.grain,
    description:
      "Solid teak frames for projects that specify traditional timber throughout. Machined to size with consistent rebates and joinery.",
    points: ["Solid teak sections", "Machined rebates", "Site-ready finish options", "Custom sections to drawing"],
  },
  {
    slug: "steamed-beech-frames",
    name: "Steamed Beech Wood Frames",
    kind: "Solid Wood",
    tagline: "Light-toned solid frames for modern interiors.",
    image: IMG.interior,
    description:
      "Solid steamed beech frames that pair with our beech and painted door programmes for a light, uniform finish.",
    points: ["Uniform pale tone", "Good paint & polish substrate", "Machined to size", "Project quantities"],
  },
  {
    slug: "lvl-door-frames",
    name: "LVL Door Frames",
    kind: "Engineered",
    tagline: "Precision-engineered frames for strength, dimensional stability and project consistency.",
    image: IMG.blueprint,
    description:
      "LVL (Laminated Veneer Lumber) frames are built from multiple thin wood veneers bonded under pressure with grains aligned. The result is an engineered frame that stays straighter and more consistent than conventional solid sections — door after door, floor after floor.",
    points: ["Engineered from laminated veneers", "High dimensional stability", "Consistent across large quantities", "Factory-machined precision"],
  },
  {
    slug: "bwp-door-frames",
    name: "BWP Grade LVL Frames",
    kind: "Engineered — BWP",
    tagline: "Boiling-water-resistant bonding for demanding conditions.",
    image: IMG.grain,
    description:
      "BWP grade LVL frames use boiling-water-proof adhesive systems for areas exposed to moisture and humidity — recommended for bathrooms, kitchens and coastal projects.",
    points: ["BWP-grade bonding", "For humid & moisture-prone areas", "Engineered stability", "Pairs with wet-area doors"],
  },
  {
    slug: "marine-grade-frames",
    name: "Marine Grade LVL Frames",
    kind: "Engineered — Marine",
    tagline: "Our highest moisture-resistance frame specification.",
    image: IMG.bathroomAlt,
    description:
      "Marine grade LVL frames are specified where water exposure is a given — wet areas, washrooms, coastal hospitality and healthcare projects.",
    points: ["Marine-grade bonding system", "Wet-area specification", "Engineered consistency", "Project documentation available"],
  },
  {
    slug: "custom-engineered-frames",
    name: "Custom Engineered Frames",
    kind: "Engineered — Custom",
    tagline: "Sections, species and build-ups engineered to your specification.",
    image: IMG.factoryFloor,
    description:
      "Custom engineered frames built to project drawings — non-standard sections, fire-rated frame build-ups and special finishes.",
    points: ["Custom sections", "Fire-rated frame build-ups", "Drawing-led production", "Sampling before supply"],
  },
  {
    slug: "red-meranti-frames",
    name: "Red Meranti Frames",
    kind: "Solid Wood",
    tagline: "Warm-toned hardwood frames for residential and hospitality projects.",
    image: IMG.interiorAlt,
    description:
      "Solid Red Meranti frames — a dependable hardwood with a warm reddish tone, machined to size with consistent rebates for project supply.",
    points: ["Solid Red Meranti sections", "Warm reddish-brown tone", "Machined rebates", "Project quantities"],
  },
  {
    slug: "red-mahogany-frames",
    name: "Red Mahogany Frames",
    kind: "Solid Wood",
    tagline: "Deep, rich-toned hardwood frames for premium interiors.",
    image: IMG.doorDark,
    description:
      "Solid Red Mahogany frames with a deep, rich tone — a premium hardwood frame option for hotels, villas and premium residential projects.",
    points: ["Solid Red Mahogany sections", "Deep rich tone", "Premium finish substrate", "Machined to size"],
  },
  {
    slug: "white-oak-frames",
    name: "White Oak Frames",
    kind: "Solid Wood",
    tagline: "Pale, strong hardwood frames with a refined grain for contemporary spaces.",
    image: IMG.living,
    description:
      "Solid White Oak frames — a pale, strong hardwood with a refined grain, suited to contemporary interiors and light finish schemes.",
    points: ["Solid White Oak sections", "Pale refined grain", "Suited to light finishes", "Machined to drawing"],
  }
];
