export const PROJECTS = [
  {
    id: 1,
    title: "Monte South",
    developer: "Adani Realty",
    application: "Veneer Finish Door Set",
    status: "Completed",
    quantity: "2500+",
    location: "Byculla",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 2,
    title: "5 Garden",
    developer: "Godrej Properties",
    application: "LVL Frame and Door",
    status: "Ongoing",
    quantity: "700+",
    location: "Matunga",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 3,
    title: "BDD Chawl",
    developer: "L&T Construction",
    application: "Red Meranti frame with Door",
    status: "Ongoing",
    quantity: "6900+",
    location: "Dadar",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 4,
    title: "BDD Chawl",
    developer: "Tata Project",
    application: "Red Meranti frame with Door",
    status: "Ongoing",
    quantity: "8100+",
    location: "Worli",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 5,
    title: "BDD Chawl",
    developer: "Shapoorji Pallonji Group",
    application: "Red Meranti frame with Door",
    status: "Ongoing",
    quantity: "6300+",
    location: "Curry Road",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 6,
    title: "Vasant Oasis",
    developer: "Sheth Creators",
    application: "LVL Frame and Door",
    status: "Completed",
    quantity: "18,000+",
    location: "Marol",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 7,
    title: "Forests & Avenue",
    developer: "Runwal Enterprises",
    application: "LVL Frame and Door",
    status: "Completed",
    quantity: "4500+",
    location: "Kanjurmarg",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 8,
    title: "Palava",
    developer: "Lodha",
    application: "Red Meranti frame with Door",
    status: "Completed",
    quantity: "25,000+",
    location: "Dombivali",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 9,
    title: "Unicorn",
    developer: "Chandak",
    application: "Red Meranti frame with Door",
    status: "Completed",
    quantity: "1500+",
    location: "Andheri",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 10,
    title: "Reserva & Tokyo Bay",
    developer: "Puranik Group",
    application: "Red Meranti frame with Door",
    status: "Completed",
    quantity: "—",
    location: "Thane",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 11,
    title: "BDD Chawl",
    developer: "Capasite Infra Projects",
    application: "Red Meranti frame with Door",
    status: "Ongoing",
    quantity: "4500+",
    location: "Worli",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: 12,
    title: "Nexzone",
    developer: "Marathon Realty",
    application: "Red Meranti frame with Door",
    status: "Completed",
    quantity: "15,000+",
    location: "Panvel",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop",
  },
];
